import Head from "next/head";
import About from "../components/About";
import Collection from "../components/Collection";
import Community from "../components/Community";
import CreateNft from "../components/CreateNft";
import Creator from "../components/Creator";
import Explore from "../components/Explore";
import Header from "../components/Header";
import Join from "../components/Join";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Raleway:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <Header />
        <Explore />
        <Creator />
        <Community />
        <About />
        <Collection />
        <CreateNft />
        <Join />
      </main>
    </>
  );
}
